-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 15:10:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopall` DEFAULT CHARACTER SET utf8mb4 ;
USE `shopall` ;

-- -----------------------------------------------------
-- Table `shopall`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`categorias` (
  `categoria_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shopall`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`roles` (
  `rol_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shopall`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`usuarios` (
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `ape_paterno` VARCHAR(100) NOT NULL,
  `ape_materno` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(13) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `rol_id` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `shopall`.`roles` (`rol_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shopall`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`productos` (
  `producto_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,0) NOT NULL,
  `detalles` VARCHAR(100) NOT NULL,
  `cant_disponible` INT(11) NULL DEFAULT NULL,
  `categoria_id` INT(11) NULL DEFAULT NULL,
  `vendedor_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`producto_id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  INDEX `vendedor_id` (`vendedor_id` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `shopall`.`categorias` (`categoria_id`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `shopall`.`usuarios` (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shopall`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`comentarios` (
  `comentario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `comprador_id` INT(11) NULL DEFAULT NULL,
  `producto_id` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`comentario_id`),
  INDEX `comprador_id` (`comprador_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`comprador_id`)
    REFERENCES `shopall`.`usuarios` (`usuario_id`),
  CONSTRAINT `comentarios_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `shopall`.`productos` (`producto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shopall`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`compra` (
  `compra_id` INT(11) NOT NULL AUTO_INCREMENT,
  `comprador_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`compra_id`),
  INDEX `comprador_id` (`comprador_id` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`comprador_id`)
    REFERENCES `shopall`.`usuarios` (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shopall`.`productos_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`productos_compra` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `compra_id` INT(11) NULL DEFAULT NULL,
  `producto_id` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id` (`compra_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `productos_compra_ibfk_1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `shopall`.`compra` (`compra_id`),
  CONSTRAINT `productos_compra_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `shopall`.`productos` (`producto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shopall`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopall`.`transacciones` (
  `transaccion_id` INT(11) NOT NULL AUTO_INCREMENT,
  `comprador_id` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `monto` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`transaccion_id`),
  INDEX `comprador_id` (`comprador_id` ASC) VISIBLE,
  CONSTRAINT `transacciones_ibfk_1`
    FOREIGN KEY (`comprador_id`)
    REFERENCES `shopall`.`usuarios` (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
